import Head from 'next/head';
import Image from 'next/image';
import { useAuth } from '../lib/auth';
import styles from '../styles/Home.module.css';

export default function Home() {
  const auth = useAuth();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Fast Feedback</h1>
        {!auth?.user && (
          <button onClick={(e) => auth.signinWithGithub()}>Sign in</button>
        )}
        <div>{auth?.user?.email}</div>
        {auth?.user && (
          <button onClick={(e) => auth.signout()}>Sign out</button>
        )}
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
